name: buf
on:
  pull_request:
    branches: [ main ]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch origin main:main

      - uses: bufbuild/buf-setup-action@v1

      - run: make lint
      - run: buf format --diff
      - run: make breaking
